name: Email Automation Job

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies (pnpm)
        run: |
          cd scripts
          pnpm install

      - name: Run script
        run: |
          cd scripts
          pnpm exec tsx src/email-to-sheets.ts
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
